-- Fiserv Snowcamp Workshop: verified queries on PAYMENTS_ANALYTICS.
--
-- Five verified queries, each guarding a definition the agent could plausibly get
-- wrong. Two of these were chosen because the agent DID get them wrong or shaky in the
-- baseline evaluation: the fee measure and the segment ranking.
--
-- Verified query SQL must use the semantic view's LOGICAL names (AUTHS.PROCESSED_VOLUME,
-- MERCHANTS.ACQUIRING_REGION), not the physical column names.
--
-- Generated by appending AI_VERIFIED_QUERIES to the output of GET_DDL, so the rest of
-- the definition is exactly what is deployed. Regenerate the same way after any change.

USE ROLE ACCOUNTADMIN;
USE DATABASE FISERV_PAYMENTS_DB;
USE SCHEMA SEMANTIC;

create or replace semantic view PAYMENTS_ANALYTICS
	tables (
		AUTHS as FISERV_PAYMENTS_DB.RAW.AUTHORISATIONS primary key (AUTH_ID) with synonyms=('authorisations','transactions','payments','card transactions') comment='One row per card authorisation attempt, June to September 2025',
		FEES as FISERV_PAYMENTS_DB.RAW.FEE_LINES primary key (FEE_LINE_ID) with synonyms=('fees','fee lines','charges') comment='Fee components per approved authorisation: interchange, scheme fee, acquirer margin, gateway fee',
		FISERV_PAYMENTS_DB.RAW.MERCHANTS primary key (MERCHANT_ID) with synonyms=('merchants','customers','businesses','accounts') comment='Merchants accepting card payments across ten Eurozone countries',
		PRODUCTS as FISERV_PAYMENTS_DB.RAW.PAYMENT_PRODUCTS primary key (PRODUCT_ID) with synonyms=('payment products','acceptance channels','devices') comment='Payment acceptance products merchants transact on'
	)
	relationships (
		AUTHS_TO_MERCHANTS as AUTHS(MERCHANT_ID) references MERCHANTS(MERCHANT_ID),
		AUTHS_TO_PRODUCTS as AUTHS(PAYMENT_PRODUCT_ID) references PRODUCTS(PRODUCT_ID),
		FEES_TO_AUTHS as FEES(AUTH_ID) references AUTHS(AUTH_ID)
	)
	facts (
		AUTHS.AUTH_AMOUNT as AUTH_AMOUNT comment='Authorised amount in EUR. NULL on a small number of records by design.',
		AUTHS.IS_APPROVED as IFF(AUTH_RESULT = 'Approved', 1, 0) comment='One when the authorisation was approved, otherwise zero',
		AUTHS.IS_CHARGEBACK as IFF(CHARGEBACK_FLAG, 1, 0) comment='One when the authorisation was later charged back',
		FEES.FEE_AMOUNT as FEE_AMOUNT_EUR comment='Fee component amount in EUR',
		FEES.ACQUIRER_REVENUE_AMOUNT as IFF(FEE_CATEGORY = 'Acquirer Revenue', FEE_AMOUNT_EUR, 0) comment='Fee amount retained by the acquirer, excluding pass-through'
	)
	dimensions (
		AUTHS.AUTH_DATE as TO_DATE(AUTH_TIMESTAMP) with synonyms=('date','transaction date','processing date') comment='Calendar date of the authorisation',
		AUTHS.AUTH_MONTH as DATE_TRUNC('month', AUTH_TIMESTAMP) with synonyms=('month','monthly') comment='Month of the authorisation. Data covers June to September 2025 only.',
		AUTHS.AUTH_RESULT as AUTH_RESULT with synonyms=('result','status','outcome') comment='Approved, Declined or Referred',
		AUTHS.DECLINE_REASON as DECLINE_REASON with synonyms=('decline reason','reason for decline','failure reason') comment='Why the authorisation was declined. NULL when approved.',
		AUTHS.ENTRY_MODE as ENTRY_MODE with synonyms=('entry mode','how the card was presented') comment='Chip and PIN, Contactless, E-commerce, MOTO or Tap to Phone',
		AUTHS.CARD_SCHEME as CARD_SCHEME with synonyms=('scheme','card network','network') comment='Visa, Mastercard, Amex or Domestic',
		AUTHS.CHARGEBACK_REASON as CHARGEBACK_REASON with synonyms=('chargeback reason','dispute reason') comment='Reason a chargeback was raised. NULL when there was no chargeback.',
		FEES.FEE_TYPE as FEE_TYPE with synonyms=('fee type','charge type') comment='Interchange, Scheme Fee, Acquirer Margin or Gateway Fee',
		FEES.FEE_CATEGORY as FEE_CATEGORY with synonyms=('fee category') comment='Pass-through (paid on to issuer or scheme) or Acquirer Revenue (retained)',
		MERCHANTS.MERCHANT_NAME as DBA_NAME with synonyms=('merchant','merchant name','business name','trading name') comment='Merchant trading name',
		MERCHANTS.MERCHANT_SEGMENT as MERCHANT_SEGMENT with synonyms=('segment','merchant size','tier') comment='SMB, Mid-Market or Enterprise',
		MERCHANTS.RISK_TIER as RISK_TIER with synonyms=('risk','risk tier','risk rating') comment='Low, Standard, Elevated or High',
		MERCHANTS.ACQUIRING_REGION as ACQUIRING_REGION with synonyms=('region','acquiring region','area') comment='Benelux, DACH, Southern Europe or Ireland and France',
		MERCHANTS.COUNTRY_CODE as COUNTRY_CODE with synonyms=('country','market') comment='Two letter country code. Ten Eurozone countries.',
		MERCHANTS.MCC as MCC with synonyms=('mcc','merchant category code') comment='Four digit merchant category code',
		MERCHANTS.MERCHANT_CATEGORY as MCC_DESCRIPTION with synonyms=('category','vertical','industry','merchant category') comment='Plain English description of the merchant category',
		PRODUCTS.PAYMENT_PRODUCT as PRODUCT_NAME with synonyms=('product','payment product','device','terminal') comment='Payment acceptance product name',
		PRODUCTS.PAYMENT_CHANNEL as CHANNEL with synonyms=('channel','acceptance channel') comment='Card present, E-commerce or MOTO'
	)
	metrics (
		AUTHS.PROCESSED_VOLUME as SUM(auths.auth_amount * auths.is_approved) with synonyms=('processed volume','volume','TPV','total payment volume','revenue','sales') comment='Total value of APPROVED authorisations in EUR. Declined and referred authorisations are excluded, because a declined transaction is never processed. Use this for any question about volume, value or throughput.',
		AUTHS.TRANSACTION_COUNT as SUM(auths.is_approved) with synonyms=('transaction count','approved transactions','number of transactions') comment='Number of APPROVED authorisations',
		AUTHS.AUTH_ATTEMPT_COUNT as COUNT(auths.AUTH_ID) with synonyms=('authorisation attempts','attempts','total authorisations') comment='Number of authorisation ATTEMPTS regardless of outcome. This is the denominator for approval rate. Do not confuse with transaction count, which counts approvals only.',
		AUTHS.APPROVAL_RATE as 100.0 * SUM(auths.is_approved) / NULLIF(COUNT(auths.AUTH_ID), 0) with synonyms=('approval rate','acceptance rate','auth rate','approval percentage') comment='Approved authorisations as a percentage of all attempts. August 2025 is materially lower than other months.',
		AUTHS.AVERAGE_TICKET as SUM(auths.auth_amount * auths.is_approved) / NULLIF(SUM(auths.is_approved), 0) with synonyms=('average ticket','average transaction value','ATV','average basket') comment='Average value of an approved authorisation in EUR',
		AUTHS.CHARGEBACK_COUNT as SUM(auths.is_chargeback) with synonyms=('chargebacks','chargeback count','disputes') comment='Number of authorisations later charged back',
		AUTHS.CHARGEBACK_RATE as 100.0 * SUM(auths.is_chargeback) / NULLIF(SUM(auths.is_approved), 0) with synonyms=('chargeback rate','dispute rate') comment='Chargebacks as a percentage of approved authorisations',
		MERCHANTS.MERCHANT_COUNT as COUNT(DISTINCT merchants.MERCHANT_ID) with synonyms=('merchant count','number of merchants','how many merchants') comment='Distinct merchants',
		FEES.TOTAL_FEES as SUM(fees.fee_amount) with synonyms=('total fees','all fees','gross fees') comment='All fee components in EUR, INCLUDING pass-through interchange and scheme fees that are paid on to the issuer and card network. This is not acquirer revenue.',
		FEES.NET_FEE_REVENUE as SUM(fees.acquirer_revenue_amount) with synonyms=('net fee revenue','acquirer revenue','net revenue','retained revenue','our revenue') comment='Fee income the acquirer retains: acquirer margin plus gateway fees. Excludes pass-through interchange and scheme fees. Use this for any question about our revenue or earnings.'
	)
	comment='Fiserv payments analytics: card authorisations, fees, merchants and acceptance products across ten Eurozone countries, June to September 2025'

  AI_VERIFIED_QUERIES (

    -- Guards the fee definition. Cortex Analyst has two plausible fee measures and the
    -- wrong one overstates income by roughly 66%. This query pins "our revenue" to the
    -- measure that excludes interchange and scheme pass-through.
    net_revenue_by_month AS (
      QUESTION 'What was our net fee revenue by month?'
      VERIFIED_AT 1788700000
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(STEWARD = alex.macdonald)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(
             PAYMENTS_ANALYTICS
             METRICS FEES.NET_FEE_REVENUE
             DIMENSIONS AUTHS.AUTH_MONTH
           ) ORDER BY AUTH_MONTH'
    ),

    -- Guards the approval-rate denominator. Dividing approvals by transaction count
    -- (which is itself approvals only) yields a constant 100%. The denominator must be
    -- authorisation ATTEMPTS.
    approval_rate_by_month AS (
      QUESTION 'What was the card authorisation approval rate by month?'
      VERIFIED_AT 1788700000
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(STEWARD = alex.macdonald)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(
             PAYMENTS_ANALYTICS
             METRICS AUTHS.APPROVAL_RATE, AUTHS.AUTH_ATTEMPT_COUNT
             DIMENSIONS AUTHS.AUTH_MONTH
           ) ORDER BY AUTH_MONTH'
    ),

    -- Guards processed volume against the fee fan-out. Fee lines are roughly three per
    -- approved authorisation, so any volume figure that traverses FEES is inflated.
    -- This query keeps volume on the AUTHS grain while still slicing by region.
    volume_by_region AS (
      QUESTION 'Show processed volume by acquiring region'
      VERIFIED_AT 1788700000
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(STEWARD = alex.macdonald)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(
             PAYMENTS_ANALYTICS
             METRICS AUTHS.PROCESSED_VOLUME
             DIMENSIONS MERCHANTS.ACQUIRING_REGION
           ) ORDER BY PROCESSED_VOLUME DESC'
    ),

    -- The August investigation. Establishes the decline-reason breakdown by month so
    -- Analyst does not answer from full-period totals, where Insufficient Funds
    -- dominates and the issuer-side spike is invisible.
    decline_reasons_by_month AS (
      QUESTION 'What were the decline reasons by month?'
      VERIFIED_AT 1788700000
      ONBOARDING_QUESTION FALSE
      VERIFIED_BY '(STEWARD = alex.macdonald)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(
             PAYMENTS_ANALYTICS
             METRICS AUTHS.AUTH_ATTEMPT_COUNT
             DIMENSIONS AUTHS.AUTH_MONTH, AUTHS.DECLINE_REASON
           ) WHERE DECLINE_REASON IS NOT NULL
             ORDER BY AUTH_MONTH, AUTH_ATTEMPT_COUNT DESC'
    ),

    -- Guards the segment ranking, which is the part that is easy to get wrong: SMB is
    -- largest by TOTAL volume even though Enterprise is the segment people assume.
    -- Average ticket is returned alongside only to show it is flat at about EUR 50 across
    -- all three segments, so the ranking is driven by merchant count and not by ticket
    -- size. The view has no merchant-count metric, so per-merchant concentration cannot
    -- be shown here and is deliberately not claimed.
    volume_by_segment AS (
      QUESTION 'Which merchant segment drives the most processed volume?'
      VERIFIED_AT 1788700000
      ONBOARDING_QUESTION TRUE
      VERIFIED_BY '(STEWARD = alex.macdonald)'
      SQL 'SELECT * FROM SEMANTIC_VIEW(
             PAYMENTS_ANALYTICS
             METRICS AUTHS.PROCESSED_VOLUME, AUTHS.AVERAGE_TICKET
             DIMENSIONS MERCHANTS.MERCHANT_SEGMENT
           ) ORDER BY PROCESSED_VOLUME DESC'
    )
  )
;
