-- Fiserv Snowcamp Workshop: Data Metric Functions and Row Access Policy.
--
-- THE DMF EXERCISE. This is the strongest teaching moment in session 4, and it
-- only works because the coverage gap is planted deliberately:
--
--   AUTHORISATIONS.AUTH_AMOUNT   NULL_COUNT attached  -> 189 NULLs detected
--   FEE_LINES.FEE_AMOUNT_EUR     NULL_COUNT attached  -> 215 NULLs detected
--   FEE_LINES.FEE_CATEGORY       NULL_COUNT attached  -> 0 NULLs, monitor is clean
--   FEE_LINES.FEE_TYPE           NOT MONITORED        -> 152 NULLs go unnoticed
--
-- Attendees are asked to check quality results, see two columns reporting
-- violations and everything else apparently clean, then discover that FEE_TYPE has
-- 152 NULLs nobody is watching because the monitor was attached to the neighbouring
-- column. They then move it. Monitor, find the gap, fix the coverage.
--
-- DO NOT "fix" the FEE_CATEGORY attachment in this script. The gap is the lesson.

USE ROLE ACCOUNTADMIN;
USE DATABASE FISERV_PAYMENTS_DB;
USE SCHEMA RAW;

-- A schedule is required before a DMF can be attached.
ALTER TABLE AUTHORISATIONS SET DATA_METRIC_SCHEDULE = '60 MINUTE';
ALTER TABLE FEE_LINES      SET DATA_METRIC_SCHEDULE = '60 MINUTE';

-- IDEMPOTENT. ADD DATA METRIC FUNCTION and ADD ROW ACCESS POLICY both error if the
-- attachment already exists (003531 / 23001). In the chained orchestrator that would abort
-- the run mid-way and leave a half-built account, so each attachment swallows that error.
--
-- EXECUTION PATH: this file must be run via EXECUTE IMMEDIATE FROM, which parses the block
-- server-side. Running it with `snow sql -f` fails, because the CLI splits statements on
-- semicolons and tears the block apart.
EXECUTE IMMEDIATE $$
BEGIN
  BEGIN
    ALTER TABLE AUTHORISATIONS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (AUTH_AMOUNT);
  EXCEPTION WHEN OTHER THEN NULL;
  END;

  BEGIN
    ALTER TABLE FEE_LINES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (FEE_AMOUNT_EUR);
  EXCEPTION WHEN OTHER THEN NULL;
  END;

  -- The deliberate mistake: this belongs on FEE_TYPE, not FEE_CATEGORY.
  BEGIN
    ALTER TABLE FEE_LINES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (FEE_CATEGORY);
  EXCEPTION WHEN OTHER THEN NULL;
  END;

  RETURN 'monitors attached';
END;
$$;

-- Row access policy on acquiring region.
-- Role-based via CURRENT_ROLE(), NOT session variables: agent evaluations cannot
-- evaluate an agent whose queries depend on session attributes.
USE SCHEMA SEMANTIC;

CREATE ROLE IF NOT EXISTS SOUTHERN_EUROPE_MANAGER;
GRANT USAGE ON DATABASE FISERV_PAYMENTS_DB TO ROLE SOUTHERN_EUROPE_MANAGER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FISERV_PAYMENTS_DB TO ROLE SOUTHERN_EUROPE_MANAGER;
GRANT SELECT ON ALL TABLES IN DATABASE FISERV_PAYMENTS_DB TO ROLE SOUTHERN_EUROPE_MANAGER;
GRANT SELECT ON ALL VIEWS IN DATABASE FISERV_PAYMENTS_DB TO ROLE SOUTHERN_EUROPE_MANAGER;
GRANT SELECT ON ALL DYNAMIC TABLES IN DATABASE FISERV_PAYMENTS_DB TO ROLE SOUTHERN_EUROPE_MANAGER;
GRANT USAGE ON WAREHOUSE FISERV_WH TO ROLE SOUTHERN_EUROPE_MANAGER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SOUTHERN_EUROPE_MANAGER;

-- IF NOT EXISTS, not OR REPLACE: a policy cannot be replaced while it is attached to a
-- table ("cannot be dropped/replaced as it is associated with one or more entities").
CREATE ROW ACCESS POLICY IF NOT EXISTS ACQUIRING_REGION_POLICY
  AS (acquiring_region VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN')
    OR (CURRENT_ROLE() = 'SOUTHERN_EUROPE_MANAGER' AND acquiring_region = 'Southern Europe')
  COMMENT = 'Restricts merchant data to the caller acquiring region. Applied transparently, including to SQL generated by Cortex Agents.';

EXECUTE IMMEDIATE $$
BEGIN
  ALTER TABLE FISERV_PAYMENTS_DB.RAW.MERCHANTS
    ADD ROW ACCESS POLICY ACQUIRING_REGION_POLICY ON (ACQUIRING_REGION);
  RETURN 'policy applied';
EXCEPTION WHEN OTHER THEN
  RETURN 'policy already applied';
END;
$$;

-- Verification: what each role can see.
SELECT 'Monitors attached' AS check_name, COUNT(*)::VARCHAR AS result
FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'FISERV_PAYMENTS_DB.RAW.FEE_LINES',
    REF_ENTITY_DOMAIN => 'TABLE'))
UNION ALL
SELECT 'Regions visible as ACCOUNTADMIN',
       COUNT(DISTINCT ACQUIRING_REGION)::VARCHAR
FROM FISERV_PAYMENTS_DB.RAW.MERCHANTS;
