name: 'fiserv_payments'
version: '1.0.0'
config-version: 2

profile: 'fiserv_payments'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fiserv_payments:
    staging:
      +schema: DBT_STAGING
      +materialized: view
    analytics:
      +schema: DBT_ANALYTICS
      +materialized: table
